language: scala

scala: 2.11.1

env:
  - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"

after_success:
  - export COVERALLS_REPO_TOKEN=KaV31nMn63pJSb6hSLsbT97lfgBtB8VEL
  - sbt coveralls
